version: 0.2

phases:
  pre_build:
    commands:
      - echo Fazendo login no ECR....
      - aws --version
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 356750587093.dkr.ecr.us-east-1.amazonaws.com
      - REPOSITORY_URI=356750587093.dkr.ecr.us-east-1.amazonaws.com/bia
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - IMAGE_TAG=${COMMIT_HASH:=latest}
      - echo "Retrieving DB credentials from Secrets Manager..."
      - SECRET=$(aws secretsmanager get-secret-value --secret-id your-secret-id --query SecretString --output text)
      - export DB_USER=$(echo $SECRET | jq -r '.db_user')
      - export DB_PWD=$(echo $SECRET | jq -r '.db_pwd')
  build:
    commands:
      - echo Build iniciado em `date`
      - echo Gerando imagem da BIA...
      - docker build -t $REPOSITORY_URI:latest .
      - docker tag $REPOSITORY_URI:latest $REPOSITORY_URI:$IMAGE_TAG
  post_build:
    commands:
      - echo Build finalizado com sucesso em `date`
      - echo Fazendo push da imagem para o ECR....
      - docker push $REPOSITORY_URI:latest
      - docker push $REPOSITORY_URI:$IMAGE_TAG
      - echo Gerando artefato da imagem para o ECS
      - printf '[{"name":"bia","imageUri":"%s"}]' $REPOSITORY_URI:$IMAGE_TAG > imagedefinitions.json
      - codebuild-breakpoint
artifacts:
  files: imagedefinitions.json
