version: "3.4"
networks:
  dev:
    driver: bridge

services:
  server:
    depends_on:
     - "database"
    container_name: bia
    ports:
      - 8080:80
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - ConnectionStrings__DefaultConnection=User ID=postgres;Password=postgres;Server=database;Port=5432;Database=bia; Pooling=true;
      - ASPNETCORE_URLS=http://+:80
    networks:
      - dev

  database:
     image: postgres:latest
     container_name: database
     environment:
       - POSTGRES_USER=postgres
       - POSTGRES_PASSWORD=postgres
       - POSTGRES_DB=bia
     ports:
       - "5433:5432"
     restart: always
     volumes:
       - db:/var/lib/postgresql/data
     networks:
       - dev

volumes:
  db:
    